boards:
  test:
    title: First Board
    items:
      -
        id: clock1
        provider: \StpBoard\Clock\ClockControllerProvider
        refresh: 0
        width: 4
#      -
#        id: clock2
#        provider: \StpBoard\Clock\ClockControllerProvider
#        refresh: 60
#        width: 4
#        params:
#          access_token: xyz
#          limit: 10
